### PR TITLE
Revamp home page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #269 
Screenshot 2024-10-21 at 2 01 43 AM
Screenshot 2024-10-21 at 2 01 53 AM
Screenshot 2024-10-21 at 2 02 02 AM

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]
This is great. Thanks for this enhancment

**Comment by shubhagarwal1** [comment]
@sanjay-kv Sir, please add labels

**Comment by sanjay-kv** [comment]
can you add auto label on merge workflow?

**Comment by shubhagarwal1** [comment]
> This is great. Thanks for this enhancment

Glad you liked it!

**Comment by shubhagarwal1** [comment]
> can you add auto label on merge workflow?

sure Sir,
Permanent labels
- gssoc-ext
- hacktoberfest-accepted 
and levels would be assigned by you accordingly, if there are more to it please give some details.

**Comment by sanjay-kv** [comment]
thats it for now

**Pull request merged**
