### PR TITLE
Enhance and structure the Contributor Section

### PR DESCRIPTION
**Pull request by alo7lika**
## Description
This pull request enhances and structures the Contributor Section to make it more visually appealing and informative.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots/videos (if applicable)
Screenshot 2024-10-28 212013

## Checklist:
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I thoroughly tested the changes before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Additional context:
This update enhances the Contributor Section layout, including refined visuals and better readability to improve user experience.

### CODE REVIEW

**Comment by alo7lika** [comment]
@sanjay-kv the task has been completed.

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
I will put some hold on this for 1 day

**Comment by alo7lika** [comment]
> I will put some hold on this for 1 day

@sanjay-kv

**Comment by alo7lika** [comment]
> I will put some hold on this for 1 day

@sanjay-kv

**Comment by alo7lika** [comment]
> I will put some hold on this for 1 day

Its been a week @sanjay-kv

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
