### PR TITLE
Enhanced Footer with Social Links ON README

### PR DESCRIPTION
**Pull request by alo7lika**
## Description
Enhanced Footer with Social Links on README to improve visibility and accessibility for users to connect on social platforms.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots/videos (if applicable)
Screenshot 2024-10-25 180223

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Additional context:
The enhanced footer now includes links to our GitHub, Twitter, and LinkedIn profiles. This will help users easily find and follow us on social media for updates and announcements.

### CODE REVIEW

**Comment by alo7lika** [comment]
@sanjay-kv the task has been completed.

**Comment by alo7lika** [comment]
Screenshot 2024-10-25 181129

ADD labels on the PR

**Comment by alo7lika** [comment]
> Screenshot 2024-10-25 181129
> 
> ADD labels on the PR

@sanjay-kv

**Review by sanjay-kv — APPROVED** [review]

**Comment by alo7lika** [comment]
> > Screenshot 2024-10-25 181129
> > ADD labels on the PR
> 
> @sanjay-kv

add labels on this PR

**Comment by alo7lika** [comment]
> > > Screenshot 2024-10-25 181129
> > > ADD labels on the PR
> > 
> > 
> > @sanjay-kv
> 
> add labels on this PR

GSSOC AND HACKTOBERFEST (SINCE IT SHOWS THE REPO IS NOT PARTICIPATING)

**Pull request merged**
